Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/__main__.py", line 5, in <module>
    from semgrep.cli import cli
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/cli.py", line 4, in <module>
    from semgrep.commands.ci import ci
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/commands/ci.py", line 15, in <module>
    from semgrep.commands.scan import CONTEXT_SETTINGS
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/commands/scan.py", line 34, in <module>
    from semgrep.rule_match_map import RuleMatchMap
ModuleNotFoundError: No module named 'semgrep.rule_match_map'
